SingerSite/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SingerSite.Models;

namespace SingerSite.Controllers
{
    [RequireHttps]
    public class MusicController : Controller
    {
        private SongDBContext db = new SongDBContext();

        // GET: /Music/
        public ActionResult Index()
        {
            var FilePaths = db.FilePaths.ToList();
            return View(db.Songs.ToList());
        }

        // GET: /Music/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SongViewModel songviewmodel = db.Songs.Find(id);
            if (songviewmodel == null)
            {
                return HttpNotFound();
            }
            return View(songviewmodel);
        }

        // GET: /Music/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Music/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,Title,Link,YouTube,Description")] SongViewModel songviewmodel, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    FilePath oFilePath = new FilePath
                    {
                        FileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName),
                        FileType = FileType.mp4,
                    };
                    songviewmodel.FilePath = oFilePath;
                    string strServerDirectory = Server.MapPath("~/uploads/music");
                    if (!Directory.Exists(strServerDirectory))
                    {
                        Directory.CreateDirectory(strServerDirectory);
                    }
                    upload.SaveAs(Path.Combine(strServerDirectory, oFilePath.FileName)); 
                }

                songviewmodel.PostDate = DateTime.Now;
                db.Songs.Add(songviewmodel);
                if(songviewmodel.FilePath != null) db.FilePaths.Add(songviewmodel.FilePath);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(songviewmodel);
        }

        // GET: /Music/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SongViewModel songviewmodel = db.Songs.Find(id);
            if (songviewmodel == null)
            {
                return HttpNotFound();
            }
            return View(songviewmodel);
        }

        // POST: /Music/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,Title,Link,YouTube,Description")] SongViewModel songviewmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(songviewmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(songviewmodel);
        }

        // GET: /Music/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SongViewModel songviewmodel = db.Songs.Find(id);
            if (songviewmodel == null)
            {
                return HttpNotFound();
            }
            return View(songviewmodel);
        }

        // POST: /Music/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            SongViewModel songviewmodel = db.Songs.Find(id);
            db.Songs.Remove(songviewmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SingerSite/Views/Music/Create.cshtml
@model SingerSite.Models.SongViewModel

@{
    ViewBag.Title = "Create";
}

<div class="box" >
    <h2>Create</h2>
    @using (Html.BeginForm("Create", "Music", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>songviewmodel</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Link)
                    @Html.ValidationMessageFor(model => model.Link)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    Content

                    <select id="FileTypeDropdown" >
                        <option value="option1">Link</option>
                        <option value="option2">File</option>
                    </select>
                </div>
                <div>
                    @*Youtube Link*@
                    <div data-option="FileTypeDropdown" id="option1" class="col-md-10">
                        @Html.EditorFor(model => model.YouTube)
                        @Html.ValidationMessageFor(model => model.YouTube)
                    </div>

                    @*Upload*@
                    <div data-option="FileTypeDropdown" id="option2" class="col-md-10">
                        <input type="file" id="Upload" name="Upload" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SingerSite/Views/Music/Delete.cshtml
@model SingerSite.Models.SongViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="container boxDynamic">
    <h4>songviewmodel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YouTube)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YouTube)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SingerSite/Views/Music/Details.cshtml
@model SingerSite.Models.SongViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="container boxDynamic">
    <h4>songviewmodel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YouTube)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YouTube)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SingerSite/Views/Music/Edit.cshtml
@model SingerSite.Models.SongViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="container boxDynamic form-horizontal" >
        <h4>songviewmodel</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link)
                @Html.ValidationMessageFor(model => model.Link)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YouTube, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YouTube)
                @Html.ValidationMessageFor(model => model.YouTube)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SingerSite/Views/Music/Index.cshtml
@model IEnumerable<SingerSite.Models.SongViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="container" data-authorization="Admin" hidden>
    <div class="boxDynamic">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    </div>
</div>
<div class="container">
    @foreach (var item in Model)
    {            
        if (item.FilePath == null)
        { 
            if(!string.IsNullOrWhiteSpace(item.YouTube))
            { 
                <div class="boxDynamic">
                    <p >
                        <strong>
                            @Html.DisplayFor(modelItem => item.Title)
                        </strong>
                    </p>
                    <iframe width="520" height="315" src=@Html.DisplayFor(modelItem => item.YouTube) frameborder="0" allowfullscreen></iframe>
                    <p>
                        @Html.DisplayFor(modelItem => item.Description)
                    </p>            
                    <p data-authorization="Admin" hidden>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </p>
                </div>
            }
        }
        else
        {
            if (item.FilePath.FileType == SingerSite.Models.FileType.mp3)
            { 
                <div class="boxDynamic">
                    <p >
                        <strong>
                            @Html.DisplayFor(modelItem => item.Title)
                        </strong>
                    </p>
                    <audio controls>
                        <source src="~/uploads/music/@item.FilePath.FileName" type="audio/mpeg">
                        Your browser does not support the audio element.
                    </audio>
                    <p>
                        @Html.DisplayFor(modelItem => item.Description)
                    </p>            
                    <p data-authorization="Admin" hidden>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </p>
                </div>
            }
            else if (item.FilePath.FileType == SingerSite.Models.FileType.mp4)
            {
                <div class="boxDynamic">
                    <p >
                        <strong>
                            @Html.DisplayFor(modelItem => item.Title)
                        </strong>
                    </p>
                    <video width="520" height="315" controls>
                        <source src="~/uploads/music/@item.FilePath.FileName" type="audio/mp4">
                        Your browser does not support the video element.
                    </video>
                    <p>
                        @Html.DisplayFor(modelItem => item.Description)
                    </p>            
                    <p data-authorization="Admin" hidden>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </p>
                </div>
            }
        }
    }
</div>