SingerSite/Controllers/NewsPostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SingerSite.Models;

namespace SingerSite.Controllers
{
    public class NewsPostController : Controller
    {
        private NewsPostDBContext _db = new NewsPostDBContext();

        private UpdateCollection _updateCollection = new UpdateCollection(new SongDBContext());

        // GET: /NewsPost/
        public ActionResult Index()
        {
            NewsIndexViewModel vm = new NewsIndexViewModel();
            vm.UpdateModels = _updateCollection.getLatestModels();
            vm.NewsPostModels = _db.NewsPosts.ToList();
            return View(vm);
        }

        // GET: /NewsPost/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsPostModel newspostmodel = _db.NewsPosts.Find(id);
            if (newspostmodel == null)
            {
                return HttpNotFound();
            }
            return View(newspostmodel);
        }

        // GET: /NewsPost/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /NewsPost/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include="ID,Content")] NewsPostModel newspostmodel)
        {
            if (ModelState.IsValid)
            {
                newspostmodel.PostDate = DateTime.Now;
                _db.NewsPosts.Add(newspostmodel);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newspostmodel);
        }

        // GET: /NewsPost/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsPostModel newspostmodel = _db.NewsPosts.Find(id);
            if (newspostmodel == null)
            {
                return HttpNotFound();
            }
            return View(newspostmodel);
        }

        // POST: /NewsPost/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include="ID,PostDate,Content")] NewsPostModel newspostmodel)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(newspostmodel).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newspostmodel);
        }

        // GET: /NewsPost/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsPostModel newspostmodel = _db.NewsPosts.Find(id);
            if (newspostmodel == null)
            {
                return HttpNotFound();
            }
            return View(newspostmodel);
        }

        // POST: /NewsPost/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsPostModel newspostmodel = _db.NewsPosts.Find(id);
            _db.NewsPosts.Remove(newspostmodel);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SingerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body onload="showAuthorizedData(@User.IsInRole("Admin"))">
    <div class="brand">Laura Serban</div>
    <div class="address-bar">Singer, Songwriter, Fitness Model</div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-2">
            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1,#bs-example-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                @Html.ActionLink("Laura Serban", "Index", "NewsPost", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("News", "Index", "NewsPost")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Music", "Index", "Music")</li>
                    <li>@Html.ActionLink("Writings", "Index", "Writings")</li>
                    <li>@Html.ActionLink("Gallery", "Index", "Gallery")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Laura Serban 2015</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Script to Activate the Carousel -->
    <script>
        $('.carousel').carousel({
            interval: 5000 //changes the speed
        })
    </script>
    <!-- Script to hide unauthorized elements -->
    <script src="../Scripts/custom.js"></script>
</body>
</html>